// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1716.DeepSpaceJosh;

import org.usfirst.frc1716.DeepSpaceJosh.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc1716.DeepSpaceJosh.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    public Joystick leftJoystick;
    public Joystick rightJoystick;
    public JoystickButton armLowerButton;
    public JoystickButton armRaiseButton;
    public JoystickButton ballInButton;
    public JoystickButton ballOutButton;
    public JoystickButton tiltIntakeDownButton;
    public JoystickButton tiltIntakeUpButton;
    public JoystickButton placeHatchButton;

    public OI() {
        leftJoystick = new Joystick(0);
        rightJoystick = new Joystick(1);
        
        armRaiseButton = new JoystickButton(rightJoystick, 5);
        armRaiseButton.whileHeld(new RaiseArmCommand());
        armLowerButton = new JoystickButton(rightJoystick, 4);
        armLowerButton.whileHeld(new LowerArmCommand());
        ballInButton = new JoystickButton(leftJoystick, 4);
        ballInButton.whileHeld(new BallInCommand());
        ballOutButton = new JoystickButton(leftJoystick, 5);
        ballOutButton.whileHeld(new BallOutCommand());
        tiltIntakeDownButton = new JoystickButton(rightJoystick, 3);
        tiltIntakeDownButton.whileHeld(new TiltIntakeDownCommand());
        tiltIntakeUpButton = new JoystickButton(rightJoystick, 2);
        tiltIntakeUpButton.whileHeld(new TiltIntakeUpCommand());
        placeHatchButton = new JoystickButton(leftJoystick, 2);
        placeHatchButton.whenPressed(new PlaceHatchCommand());
        
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("Lower Arm Command", new LowerArmCommand());
        SmartDashboard.putData("Raise Arm Command", new RaiseArmCommand());
        SmartDashboard.putData("Drive Command", new DriveCommand());
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getLeftJoystick() {
        return leftJoystick;
    }

    public Joystick getRightJoystick() {
        return rightJoystick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

