// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1716.DeepSpaceJosh.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc1716.DeepSpaceJosh.Robot;

/**
 *
 */
public class RaiseArmCommand extends Command {

    private int count = 0;

    public RaiseArmCommand() {
        requires(Robot.armSubsystem);
    }

    @Override
    protected void initialize() {
        count = 0;
        Robot.armSubsystem.solenoidForward();
    }

    @Override
    protected void execute() {
        if (count == 5)
        {
            Robot.armSubsystem.solenoidOff();
            if (!Robot.armSubsystem.getSwitchBottom())
                Robot.armSubsystem.setArmMotor(1.0);
        }
    	count++;
    }

    @Override
    protected boolean isFinished() {
        if (Robot.armSubsystem.getSwitchBottom())
            return true;
        return false;
    }

    @Override
    protected void end() {
    	Robot.armSubsystem.setArmMotor(0);
    }

    @Override
    protected void interrupted() {
        Robot.armSubsystem.solenoidOff();
    	Robot.armSubsystem.setArmMotor(0);
    }
}